@baseUrl = http://localhost:3000


# Recados
### Lista todos os recados, query parameters
GET  {{baseUrl}}/recados/
# ?limit=10
# &offset=10
# &user=mateus
### apenas um recado
GET  {{baseUrl}}/recados/2/
### criar novo recado e me permite enviar coisas
POST  {{baseUrl}}/recados/
Content-Type: application/json

 {
    "texto": "Novo Recado",
    "de": "Joana",
    "para": "João"

}

### atualizar apenas um recurso com Path
PATCH   {{baseUrl}}/recados/5/
Content-Type: application/json

{
    "texto": "Recado atualizado 2",
    "de": "Joana",
    "para": "João"

}

### apaga um recado
DELETE  {{baseUrl}}/recados/2/





### Pessoas

# Pessoas
### Lista todas as pessoas, query parameters
GET  {{baseUrl}}/pessoas/
# ?limit=10
# &offset=10
# &user=mateus
### apenas uma pessoa
GET  {{baseUrl}}/pessoas/2/
### criar novo recado e me permite enviar coisas
POST  {{baseUrl}}/pessoas/
Content-Type: application/json

 {
    "nome": "Joao",
    "email": "joao11@email.com",
    "password": "senha123"

}

### atualizar apenas um recurso
PATCH   {{baseUrl}}/pessoas/8/
Content-Type: application/json

{
    "password": "senha6543",
    "nome": "Joao"

}

### apaga uma pessoa
DELETE  {{baseUrl}}/pessoas/7/











### AppControllerGetHello

# @name AppControllerGetHello
GET  {{baseUrl}}/

### ExemploDeRota

# @name ExemploDeRota
GET  {{baseUrl}}/exemplo

### ConceitosManualController Home

# @name ConceitosManualControllerHome
GET  {{baseUrl}}/conceitos-manual

### ConceitosAutomaticoController Home

# @name ConceitosAutomaticoController
GET  {{baseUrl}}/conceitos-automatico

